### ISSUE TITLE
Matlab cannot read the xls file

### ISSUE THREAD

**Issue by meleantonio** [chrishawes007/ECO2048#1]
It may be due to the fact that the first column of the excel file doesn't have a name? or maybe the format is wrong? @chrishawes007 

I receive the following error message:

```
Error using readtable (line 197)
Error: File: readXLSFile.m Line: 53 Column: 8
Arguments to IMPORT must either end with ".*" or else specify a fully qualified class name:
"matlab.io.spreadsheet.internal.readSpreadsheetFile" fails this test.

Error in workingproject (line 5)
T = readtable('samplematlab2.xls','ReadRowNames',true);
```

**Comment by chrishawes007** [comment]
There is no name above the first column because the names in that column are used as the row names but I haven't had this error message when testing the code, it always runs through fine so far.

I will look into this and see if I can understand what is going wrong.

**Comment by meleantonio** [comment]
sorry I think it's just me, I just fucked up with Matlab and I have to reinstall it. Forget about it.

**Comment by meleantonio** [comment]
yes, now working fine. sorry about that.
